[package]
name = "cli"
version = "0.1.7"
edition = "2021"

[dependencies]
core = { path = "../core" }
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.15", features = ["derive"] }
